PrefectHQ/vue-compositions

README.md
src/media/README.md
src/media/media.ts
src/subscribe/README.md
src/subscribe/createActions.ts
src/subscribe/index.ts
src/subscribe/subscribe.ts
src/subscribe/types.ts

Its a community standard for compositions to follow the `useThing` naming convention. Adding aliases for both `media` and `subscribe` that use this naming convention. `media` and `subscribe` are now deprecated in favor of `useMedia` and `useSubscription`
Included in this PR are a couple quality of life improvements around creating subscriptions. When using `useSubscription` the `args` argument is no longer required when the action has no required arguments. This means it's no longer necessary to pass in an empty array like `useSubscription(myAction, [])`. You can just use `useSubscription(myAction)`
Using `useSubscription` with classes or objects has been inconvenient because of the binding issue with actions. This PR introduces a new utility called `createActions` that helps make using …

Composition Aliases and Subscription Quality of Life Improvements

---

package.json
src/subscribe/createActions.ts

`Record<string, unknown>` made createActions throw a type error if you passed in a class instance. Change it to any correctly errors for simple values while allowing class instances to work.

Bug: Fix types not working for class instances when using createActions

---

package.json
src/subscribe/createActions.ts
tests/subscribe/createActions.spec.ts

Update the logic that gets instance members to only return members that are functions.

Bugfix: Ignore non function members like getters

---

package.json
src/subscribe/createActions.ts
tests/subscribe/createActions.spec.ts

`createAction` would return the overridden members rather than the overrides. Checking if the action was already added prevents that from happening. Added test to confirm.

BugFix: createActions overridden members

---

src/subscribe/channel.ts
src/subscribe/subscribe.ts
src/subscribe/subscription.ts
src/subscribe/utilities.ts
tests/subscribe/useSubscription.spec.ts

When a subscription contains reactive arguments a couple of unexpected things can happen.
1. When arguments change the subscriptions channel changes. If a new channel has been created the subscriptions response would be undefined until the action resolves. 
2. When a new subscription to an existing channel is creating the response is undefined until the action is executed again.
3. If not all the arguments are reactive, vue would log a warning in the console. Ultimately the subscription was working as expected (we don't want vue to update the subscription if a non-reactive argument is changed anyway). But this causes confusion.
When a subscriptions channel is changed, if that channel is new it's response will be `undefined`. When that is the case, retain the previous channels response. …

Fix response undefined and vue watch warnings

---

src/subscribe/README.md
src/subscribe/subscribe.ts
src/subscribe/types.ts
tests/subscribe/useSubscription.spec.ts
tests/utils.ts

Reduce the number of arguments of subscribe by moving the `manager` argument into the `options` arguments. Make wrapping subscribe in other projects simpler.

Make manager part of the subscription options

---

src/subscribe/channel.ts
src/subscribe/subscription.ts
tests/subscribe/useSubscription.spec.ts

If an action throws an error we don't need to keep executing the action as the response will not change. 
Also modified how channels and subscriptions keep track of the public date (loading, executed, response, etc) so that the channel has a copy. That way when a subscription is created it can be created with the data the channel already has. Previously only response and executed were populated when a subscription was created.

Stop interval if action errors

---

README.md
src/index.ts
src/useElementWidth/README.md
src/useElementWidth/index.ts
src/useElementWidth/useElementWidth.ts

The `useElementWidth` composition abstracts away the logic for tracking the client width of an HTMLElement, even when the client width changes on resize thanks to `useResizeObserver`.
```typescript
import { useElementWidth } from '@prefecthq/vue-compositions'
const templateRef = ref<HTMLElement | undefined>()
const widthInPx = useElementWidth(templateRef)
```
| Name     | Type                              |
|----------|-----------------------------------|
| element | `HTMLElement \| undefined \| Ref<HTMLElement \| undefined>` |
`Ref<number>` (in px)

Feature: new composition `useElementWidth

---

README.md
package-lock.json
package.json
src/index.ts
src/useDebouncedRef/README.md
src/useDebouncedRef/index.ts
src/useDebouncedRef/useDebouncedRef.ts

The `useDebouncedRef` gives you a debounced copy of your input ref but it delays updating the copy by using a debounce. 
```typescript
import { useDebouncedRef } from '@prefecthq/vue-compositions'
const foo = ref(0)
const bar = useRouteQueryParam(foo, 1000)
foo.value++
bar // 0
setTimeout(() => {
bar // 1
}, 1000)
```
| Name         | Type                   | Default |
|--------------|------------------------|---------|
| input        | `Ref<any>`             | None    |
| wait         | `Ref<number> | number` | None    |
`Ref<T>`

useDebouncedRef

---

src/useRouteQueryParam/useRouteQueryParam.ts

Fixes bug where changing the value back to the default value didn't remove it from the url

useRouteQueryParam: Check if the value has changed or if it is the default

---

src/useSubscription/useSubscription.ts
tests/useSubscription/useSubscription.spec.ts

Previously the argument watcher would set the response of a new subscription that had a nullish response equal to the response of the initial subscription. The correct behavior is that it would set a nullish response equal to the previous response value.

BugFix: useSubscription argument watcher incorrectly setting response

---

src/useSubscription/useSubscription.ts

Previously when using `useSubscription` you would get a completely fresh subscription except for the `response`. If the previous subscription had a response it would get copied over to the new subscription. This preserved the response until the new subscription was executed.
This PR adds that same behavior to the `executed` property. This is useful because frequently `executed` is used to determine if a subscriptions action has been called at least once without having to care about what the response is. 
Preserving the `executed` property even when args change makes more sense also because `executed` applies to the action and the action for a subscription cannot be changed. 
Its worth noting that this does not yet apply to `useSubscriptionWithDependencies`. That composition will require …

Feature: useSubscription - Keep the executed value when args change

---

src/useSubscription/models/channel.ts

Subscriptions catch errors to prevent breaking reactivity. However this makes debugging difficult. Logging the error should make the developer experience better.

Feature: Log errors to the console

---

README.md
src/index.ts
src/useElementRect/README.md
src/useElementRect/index.ts
src/useElementRect/useElementRect.ts
src/useElementWidth/useElementWidth.ts

same as `useElementWidth` but includes `height`, `x`, and `y`

Feature: Use element rect

---

src/useResizeObserver/useResizeObserver.ts

updated useResizeObserver.observe methods to accept plain HTMLElement as well as Ref

Feature: useResizeObserver accept non-refs

---

package-lock.json
package.json
src/useComputedStyle/useComputedStyle.ts
src/useMutationObserver/README.md
src/useMutationObserver/useMutationObserver.ts

as documented under `options`, at least one is required else an error is thrown
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe

chore: added support for the required mutation observe options

---

src/useRouteQueryParam/useRouteQueryParam.ts

Currently the `useRouteQueryParam` uses two watchers. Those watcher run until the component's unmounted hook runs, which is actually after the route changes. Using the `beforeRouteLeave` hook from vue-router ensures that these watchers are stopped prior to the route changing. 
Fix fixes a bug where query params would stick around when navigating way from a route.

BugFix: stop watchers during the `beforeRouteLeave` lifecycle

---

README.md
src/useStorage/README.md
src/useStorage/useStorage.ts

previously, if you defined T as `const {set} = useLocalStorage<number | null>('key')`
the `set` method would not accept `null` as a valid argument, even though T claims to support null.

BugFix: support nullable types in useStorage

---

src/useStorage/storage.ts

if useStorage is used on previously saved value, this will prevent console error and allow safe transition
for example, color mode was previously saved to localStorage with simple
```ts
localStorage.setItem(colorModeLocalStorageKey, mode)
// mode is string, like 'achromatopsia'
```
if your user had 'achromatopsia' in localStorage, and you try updating to useStorage
```ts
const { value } = useStorage(colorModeLocalStorageKey)
```
you'll get the error
> Uncaught SyntaxError: Unexpected token 'a', "achromatopsia" is not valid JSON
with this PR, you'll be able to write 
```ts
const nonJsonVersion = localStorage.getItem(colorModeLocalStorageKey)
const defaultValue = isColorMode(nonJsonVersion) ? nonJsonVersion : null
```
which safely transfers the `nonJsonVersion` in

BugFix: useStorage better support transferring old storage values

---

src/useStorage/useStorage.ts

Fixes a bug where calling `remove` on storage adds the key back with the string `null`
Related to https://github.com/PrefectHQ/nebula-ui/issues/1893

BugFix: useStorage - Prevent future updates to storage once remove has been called

---

.github/workflows/release.yml
package.json

Mirroring what we've done in other repositories

Chore: Remove changelog from the release workflow and add release npm scripts

---

README.md
src/useVisibilityObserver/README.md
src/useVisibilityObserver/index.ts
src/useVisibilityObserver/useVisibilityObserver.ts

This PR adds the `useVisibilityObserver` composition that is based on `useIntersectionObserver` composition to abstract away the logic for creating and connecting an IntersectionObserver and returns a boolean value if the target element is visible

Feature: Create useVisibilityObserver

---

src/useRouteQueryParam/useRouteQueryParam.ts
src/useValidation/useValidation.ts
src/utilities/variables.ts

Adds a check in the value watcher of useValidation so that validation doesn't accidentally get run prematurely.

BugFix: useValidation validation values that haven't changed

---

src/useSubscription/models/subscription.ts
src/useSubscription/types/subscription.ts
src/useSubscription/utilities/subscriptions.ts

Fixes the types returned by the `promise` method on a subscription so that the response is not possibly undefined. 
```typescript
function action(): boolean {}
const { response } = await useSubscription(action).promise()
// before
response // boolean | undefined
// after
response // boolean

Enhancement: subscription promise types

---

src/useRouteQuery/useRouteQuery.ts

Fixes two bugs. Also has the proxy throw an error if an invalid property is used rather than just silently failing.

BugFix: Fix array query params not updating and fix query params flashing 

---

src/types/generics.ts
src/useRouteQueryParam/useRouteQueryParam.ts
src/useRouteQueryParams/useRouteQueryParams.ts

`RouteQueryParamsSchema` didn't support params that were arrays. Introducing a `NonArray` generic type that is used to get the type for a `MaybeArray` and using that in the `RouteQueryParamsSchema` type. 
Also exposed the optional `prefix` argument in the `useRouteQueryParams` composition since that will be useful in implementation.

Enhancement: Support arrays in RouteQueryParamsSchema type

---

src/useValidation/ValidationExecutor.ts
src/useValidation/useValidation.ts
src/useValidationObserver/useValidationObserver.ts

Convert the third argument of a ValidationRule from a single `signal` to a context argument that exposes additional information about the context of the validation. 
```typescript
export type ValidationRuleContext<T> = {
signal: AbortSignal,
source: string | undefined,
previousValue: T | undefined,
}
```
This allows rules to be more dynamic based on what triggered the validation. 
Also added `void` to the return type for a `ValidationRule`. If a rule returns void its a no op. Meaning it will remain in whatever state it was previously.

Enhancement: Expand functionality of validation rules

---

src/useRouteQueryParam/formats/RouteParam.ts
src/useRouteQueryParam/useRouteQueryParam.ts
src/useRouteQueryParams/useRouteQueryParams.ts

Updates the `useRouteQueryParam` and `useRouteQueryParams` compositions to allow for explicitly setting the schema value as an array. 
This is technically a breaking change. But labeling this a bugfix since the previous implementation did not allow for `string[] | undefined` params without a default value of `[]`.

Bugfix: Update to query param compositions to allow explicit array params

---

src/useRouteQueryParams/useRouteQueryParams.ts

It was discriminating things like `boolean` into `RouteParamClass<true> | RouteParamClass<false>` which breaks everything. Combined the check that removed undefined values with other conditions which fixes the issues.

BugFix: Fix params schema type discriminating to much

---

src/useRouteQueryParam/useRouteQueryParam.ts

Using a get/set based off of the route query means a param's reactivity effects are triggered whenever the route query is changed even if that specific param's value didn't change. Returning a plain ref and using watchers to sync it with the route prevents that from happening.

Enhancement: useRouteQueryParam reactivity to aggressive

---

src/useDebouncedRef/useDebouncedRef.spec.ts
src/useDebouncedRef/useDebouncedRef.ts

`useDebouncedRef` returns `Ref<T>` but if you set the value of that ref nothing happens. The intent of this composition is that the refs are the same but that there is a reactivity delay for the debounced version. This update will sync the value from the debounced ref back to the input ref (immediately). 
I also added some unit tests for this composition

Enhancement: Sync value to input ref if debounced ref is set in useDebouncedRef

---

src/useVisibilityObserver/useVisibilityObserver.ts

Usually a ref is created just to be passed in. We can make the ref optional and return the ref in the response so creating a ref is optional.

Enhancement: Make element ref optional in useVisibilityObserver

---

src/useSubscription/types/subscription.ts
src/useSubscription/useSubscription.spec.ts
src/useSubscription/useSubscription.ts
src/useSubscription/useSubscriptionWithDependencies.ts
src/utilities/tests.ts

This PR slightly changes the behavior of the `useSubscription` composition, which previously took a static `options` argument, to instead take either a static `options` argument or a `Ref`. The composition now reacts to options changes and modifies the resulting subscription accordingly. 
Example:
```ts
const num = ref(0)
const interval = ref(1000)
function incNum(): void {
num.value += 1
}
function toggleInterval(): void {
interval.value = interval.value === Infinity ? 1000 : Infinity
}
const subscriptionOptions = computed<SubscriptionOptions>(() => {
return {
interval: interval.value,
}
})
useSubscription(incNum, [], subscriptionOptions)
```
In the above example, when `interval` is set to `Infinity`, `num` will stop incrementing. When `interval` is set to `1000` again, it will …

Enhancement: `useSubscription` reactive options [RFC]

---

src/useIntersectionObserver/useIntersectionObserver.ts

Updates the `options` argument to be `Maybe<UseIntersectionObserverOptions>` and updates the internal logic to tear down the existing observer and create a new one when options change. It does this while keeping track of elements that are currently being observed.
Closes https://github.com/PrefectHQ/vue-compositions/issues/220

Enhancement: Update useVisibilityObserver to use reactive options

---

src/useSubscription/types/subscription.ts
src/useSubscription/useSubscription.spec.ts
src/useSubscription/useSubscription.ts

when creating a subscription, you now have the option of passing in a `lifecycle` argument to override the default behavior to unsubscribe on component unmount. 
```ts
const livesForever = useSubscription(myCoolFunction, [], { lifecycle: 'app' })
```
even when the component that calls `useSubscription` in it's setup gets unmounted, the manager will retain the subscription and any data fetched for the life of the app.

Feature: added lifecycle option to useSubscription

---

src/useSubscription/models/channel.ts

Each time a channel executes the action it sets the response value on the cannel itself and on each subscription to that channel. The response on a subscription is a `ref` which means assigning it triggers reactive effects. Trigger reactive effects can cascade and cause quite a bit of processing/rendering. 
This has caused issues with dependent subscriptions refreshing unnecessarily (fixed by `uniqueValueWatcher`) and computed values and component templates being re-evaluated. Technically this is correct because the ref was assigned and everything that depends on that ref should be re-evaluated. 
However this is usually not desired if the actual value of the subscription has not changed. If an action returns the same value as the previous execution, there is no need to trigger effects. …

Enhancement: Channel response reactivity
